---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: hello
spec:
  rules:
    - host: kubernetes.docker.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: hello
spec:
  type: ClusterIP
  selector:
    app: web
    version: 2.0.0
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 50002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hello
spec:
  selector:
    matchLabels:
      app: web
      version: 2.0.0
  replicas: 5
  template:
    metadata:
      labels:
        app: web
        version: 2.0.0
    spec:
      containers:
      - name: web
        image: "gcr.io/google-samples/hello-app:2.0"
        env:
        - name: "PORT"
          value: "50002"
        - name: "TEST"
          value: "500"