---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: py-hw
spec:
  ingressClassName: nginx
  rules:
    - host: kps.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: py-hw

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: py-hw
spec:
  type: ClusterIP
  selector:
    app: web
    version: 2.0.0
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8890

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: py-hw
spec:
  selector:
    matchLabels:
      app: web
      version: 2.0.0
  replicas: 2
  template:
    metadata:
      labels:
        app: web
        version: 2.0.0
    spec:
      containers:
        - name: web
          image: "python_helloworld_server:1.0"
          ports:
            - containerPort: 8891
              protocol: TCP
          imagePullPolicy: Never
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"